config/routes.rb
MadeInSyriaFR::Application.routes.draw do
  root  'posts#index'
  match '/about',   to: 'static_pages#about',   via: 'get'

  resources :users
  match '/signup', to: 'users#new', via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :posts
  match '/newpost',     to: 'posts#new',      via: 'get'
  match '/admin/posts', to: 'posts#admin',    via: 'get'
  match '/preview/:id', to: 'posts#preview',  via: 'get', as: :preview

  resources :categories
  match '/newcategory', to: 'categories#new', via: 'get'

  resources :contacts, only: [:new, :create]
  match '/contact', to: 'contacts#new', via: 'get'

  match '/feed', to: 'posts#feed', :format => 'rss', via: 'get'

  resources :media

end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user
  has_and_belongs_to_many :categories
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true
  validates :user_id, presence: true

  #Picture management
  has_attached_file :illustration, :styles => { :medium => "600x250>", :thumb => "200x200>" }, :default_url => "/images/:style/missing.jpeg"

  #Will_paginate count per page
  def self.per_page
    20
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy, :edit]
  before_action :authorized_user, only: [:destroy, :edit, :preview]

  def index
    @posts = Post.where(:published => true).paginate(page: params[:page], :per_page => 5)
    @featured = Category.find_by(name: "featured").posts.friendly.where(published: true).find(:all, :limit => 3)
  end

  def show
    @post = Post.friendly.where(published: true).find(params[:id])
  end

  def preview
    @post = Post.friendly.find(params[:id])
  end

  def new
    @post = Post.new
    @category = Category.all
  end

  def create
    if params[:post][:excerpt].empty?
      params[:post][:excerpt] = build_excerpt(params[:post][:content])
    end
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to root_url
    else
      render "new"
    end
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    if params[:post][:excerpt].empty?
      params[:post][:excerpt] = build_excerpt(params[:post][:content])
    end
    @post = Post.friendly.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Post updated"
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    Post.friendly.find(params[:id]).destroy
    flash[:success] = "Post deleted."
    redirect_to posts_url
  end

  def admin
    @posts = Post.paginate(page: params[:page])
  end

  def feed
    @posts = Post.friendly.where(published: true).find(:all)
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :illustration, {:category_ids => []}, :excerpt, :published)
    end

  def authorized_user
    @post = Post.friendly.find(params[:id]).user_id
    if !current_user?(@post) && !current_user.admin?
      redirect_to(root_url)
    end
  end

  def build_excerpt(text, max_sentences = 8, max_words = 450)
    three_sentences = text.split('. ').slice(0, max_sentences).join('. ')
    shortened = three_sentences.split(' ').slice(0, max_words).join(' ')
    shortened = Nokogiri::HTML::DocumentFragment.parse(shortened).to_html
    return shortened
  end
end

app/views/posts/_post.html.erb
<% provide(:meta, post.excerpt) %>
<div class="page-header">
  <h1><%= post.title %></h1> in 
  <% post.categories.each do |c| %>
    <%= link_to c.name, c %>
  <% end %>
  <div class="social-likes">
    <div class="facebook" title="Share link on Facebook">Facebook</div>
    <div class="twitter" title="Share link on Twitter">Twitter</div>
    <div class="plusone" title="Share link on Google+">Google+</div>
    <div class="pinterest" title="Share image on Pinterest" data-media="">Pinterest</div>
  </div>
</div>
<li>
  <p>
    <%= link_to image_tag(post.illustration.url(:thumb)), post.illustration.url, class: 'thumb fancybox' %>
    <%= sanitize post.content %>
  </p>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago by <%= link_to post.user.name, post.user %>. <% if signed_in? && current_user.admin? %>
    | <%= link_to "Delete", post, method: :delete, data: { confirm: "You sure?" } %>
    | <%= link_to "Edit", edit_post_path(post.id) %> <% end %>
  </span><br /><br />
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">About the author</h3>
    </div>
    <div class="panel-body">
      <%= gravatar_for post.user %> <%= post.user.about %>
    </div>
  </div>
  <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'madeinsyria'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</li>

app/views/posts/admin.html.erb
<% provide(:title, 'Posts Admin') %>
<div class="page-header">
  <h1>Posts Admin</h1>
</div>
<h2><%= link_to "New post", new_post_path %></h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Posted on</th>
      <th>Author</th>
      <th>Categories</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
    <tr>
      <td>
      <% if post.published %>
        <%= link_to post.title, post %>
      <% else %>
        <%= link_to post.title, preview_path(post.id) %>
      <% end %>
      </td>
      <td><%= post.created_at %></td>
      <td><%= link_to post.user.name, post.user %></td>
      <td>
        <% post.categories.each do |category| %>
          <%= category.name %>,
        <% end %>
      </td>
      <td>    
        <% if signed_in? && current_user.admin? %> 
          <%= link_to "Delete", post, method: :delete, data: { confirm: "You sure?" } %>
          | <%= link_to "Edit", edit_post_path(post.id) %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

app/views/posts/edit.html.erb
<% provide(:title, 'Edit post') %>
<div class="page-header">
  <h1>Edit post</h1>
</div>

<div class="span6 offset3">
  <%= form_for(@post) do |f| %>
    <%= render 'shared/error_messages_post' %>
    
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'%>

    <%= f.label :excerpt %>
    <%= f.text_area :excerpt, class: 'form-control', :rows => 3, :cols => 80 %>

    <%= f.label :illustration %>
    <%= f.file_field :illustration, class: 'form-control' %><br />

    <%= link_to "Upload an image", new_medium_path, :target => '_blank' %> <%= link_to "Use an image", media_path, :target => '_blank' %><br /><br />

    <%= f.label :content %>
    <%= f.text_area :content , class: 'form-control tinymce', :rows => 20, :cols => 80, :class => 'ckeditor' %>
    
    <script type="text/javascript">
    $('.ckeditor').ckeditor({});
    </script><br />

    <% categories_array = Category.all.map { |category| [category.name, category.id] } %>
    <%= f.select :category_ids, options_for_select(categories_array), {class: 'form-control'}, { :multiple => true } %>

    <%= f.label :published %>
    <%= f.check_box :published %>

    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="center jumbotron">
  <div class="jcarousel-wrapper">
    <div class="jcarousel">
      <ul>
        <% @featured.each do |f| %>
          <li>
            <div class="excerpt">
                <%= image_tag f.illustration.url(:thumb), class: 'thumb' %>
                <h1><%= link_to f.title, f %></h1>
                <p><%= sanitize f.excerpt %></p>
            <div>
          </li>
        <% end %>
    </ul>
    <span class="jcarousel-control-prev glyphicon glyphicon-circle-arrow-left"></span>
    <span class="jcarousel-control-next glyphicon glyphicon-circle-arrow-right"></span>
    </div>
  </div>
</div>

<% provide(:title, 'For a Geek New World') %>

<ul class="posts">
    <% @posts.each do |post| %>
    <li><h1 class="title"><%= link_to post.title, post %></h1>
      <p>
        <%= link_to image_tag(post.illustration.url(:thumb)), post, class: 'thumb' %>
        <%= sanitize post.excerpt %>
        <br /><%= link_to "--> Read More", post %>
      </p>
      <span class="timestamp">
        Posted <%= time_ago_in_words(post.created_at) %> ago by <%= link_to post.user.name, post.user %>. <% if signed_in? && current_user.admin? %>
        | <%= link_to "Delete", post, method: :delete, data: { confirm: "You sure?" } %>
        | <%= link_to "Edit", edit_post_path(post.id) %> <% end %>
      </span>
    </li>
    <% end %>
</ul>
<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

app/views/posts/new.html.erb
<% provide(:title, 'New post') %>
<div class="page-header">
  <h1>New post</h1>
</div>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@post) do |f| %>
      <%= render 'shared/error_messages_post' %>
      
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :excerpt %>
      <%= f.text_area :excerpt, class: 'form-control', :rows => 3, :cols => 80 %>

      <%= f.label :illustration %>
      <%= f.file_field :illustration, class: 'form-control' %><br />

      <%= link_to "Upload an image", new_medium_path, :target => '_blank' %> <%= link_to "Use an image", media_path, :target => '_blank' %><br /><br />

      <%= f.label :content %>
      <%= f.text_area :content , class: 'form-control tinymce', :rows => 20, :cols => 80, :class => 'ckeditor' %>
      
      <script type="text/javascript">
      $('.ckeditor').ckeditor({});
      </script><br />

      <% categories_array = Category.all.map { |category| [category.name, category.id] } %>
      <%= f.select :category_ids, options_for_select(categories_array), {class: 'form-control'}, { :multiple => true } %>

      <%= f.label :published %>
      <%= f.check_box :published %>

      <%= f.submit "Post", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/preview.html.erb
<% provide(:title, @post.title) %>
<%= render @post %>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<%= render @post %>