config/routes.rb
MadeInSyriaFR::Application.routes.draw do
  root  'posts#index'
  match '/about',   to: 'static_pages#about',   via: 'get'

  resources :users
  match '/signup', to: 'users#new', via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :posts
  match '/newpost',     to: 'posts#new',      via: 'get'
  match '/admin/posts', to: 'posts#admin',    via: 'get'
  match '/preview/:id', to: 'posts#preview',  via: 'get', as: :preview

  resources :categories
  match '/newcategory', to: 'categories#new', via: 'get'

  resources :contacts, only: [:new, :create]
  match '/contact', to: 'contacts#new', via: 'get'

  match '/feed', to: 'posts#feed', :format => 'rss', via: 'get'

  resources :media

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    By MadeInSyria a.k.a. Omar Alaouf
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact",   contact_path %></li>
      <li><%= link_to "Login",   signin_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="navbar-wrapper">
    <div class="container">
      <div class="navbar-default navbar-static-top" role="navigation">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>  
              <span class="icon-bar"></span>
            </button>
            <%= link_to "MadeInSyria.fr", root_path, id: "logo" %>
          </div>
          <div class="collapse navbar-collapse">
            <nav>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home",    root_path %></li>
                <li><%= link_to "About",    about_path %></li>
                <li><%= link_to "Contact", contact_path %></li>
                <% if signed_in? %>
                 <% if current_user.admin? %>
                    <li id="fat-menu" class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Admin <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <li><%= link_to "Users", users_path %></li>
                        <li><%= link_to "Categories", categories_path %></li>
                        <li><%= link_to "Posts", admin_posts_path %></li>
                        <li><%= link_to "Media", media_path %></li>
                      </ul>
                    </li>
                  <% end %>
                  <li id="fat-menu" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Sign out", signout_path, method: "delete" %>
                      </li>
                    </ul>
                  </li>
                <% end %>
              </ul>
            </nav>
          </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="col-md-1">
  <h3>Categories</h3>
  <ul>
    <% Category.all.each do |category| %>
    <li><%= link_to category.name, category %> (<%= category.posts.count %>)</li>
    <% end %>
  </ul>
  <h3>Follow me !</h3>
  <a href="https://facebook.com/MadeInSyria"><%= image_tag "facebook.png", size: "64"%></a><a href="http://www.linkedin.com/in/alaoufomar/en"><%= image_tag "linkedin.png" , size: "64"%></a><a href="https://twitter.com/MadeInSyria"><%= image_tag "twitter.png", size: "64" %></a><%= link_to image_tag("rss.png", size: "64"), feed_path %>
  <h3>Links</h3>
  <ul>
    <li><a href="https://github.com/MadeInSyria">My Github</a></li>
    <li><a href="http://notes.depad.fr/">Notes de Pad</a></li>
    <li><a href="http://sanfrancisco.sylvainkalache.com/">Sylvain Kalache</a></li>
    <li><a href="http://www.underthesidra.com/">Under the Sidra</a></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%= meta_description(yield(:meta)) %>" />
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <% flash.each do |key, value| %>
            <div class="<%= flash_class(key) %>">
                  <%= value %>
            </div>
          <% end %>
          <%= yield %>
          <%= render 'layouts/footer' %>
          <%= debug(params) if Rails.env.development? %>
        </div>
        <%= render 'layouts/sidebar' %>
      </div>
    </div>
  </body>
</html>